version: "3.4"

services:
  api-food-order:
    container_name: api-food-order
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:
      MONGO_URI:
      REDIS_HOST:
      REDIS_PORT:

  web-food-order:
    container_name: web-food-order
    build:
      context: ./apps/web-food
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:

  mongo-food-order:
    container_name: mongo-food-order
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  redis-food-order:
    container_name: redis-food-order
    image: redis:5-alpine
