version: '3.4'

services:
  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:
      MONGO_URI:
      REDIS_HOST:
      REDIS_PORT:

  web-food:
    container_name: web-food
    build:
      context: ./apps/web-food
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:

  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  redis:
    container_name: redis
    image: redis:5-alpine
