version: "3.4"

services:
  api-food-order:
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - ./apps/api:/usr/app

  web-food-order:
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0
    volumes:
      - ./apps/web-food:/usr/app

  mongo-express-food-order:
    container_name: mongo-express-food-order
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: "mongo-food-order"
